#!/bin/bash

bspc monitor -d conf dev src chill

for desktop in $(bspc query -D); do
  bspc config -d $desktop border_width 5
  bspc config -d $desktop window_gap 20
  bspc config -d $desktop focused_border_color "#dadada"
done

bspc config top_padding 50
bspc config right_padding 30

bspc config left_padding 30
bspc config bottom_padding 30

bspc config focus_follows_pointer true

killall -q polybar
polybar -c $HOME/Projects/configs/polybar.ini
bash $HOME/bin/polybar_mk.sh
